import tkinter
from tkinter import *
from tkinter import ttk
import Controller
from PIL import ImageTk, Image 

GUI = Tk();
GUI.title('Language Translate');
GUI.geometry('765x450');

def main_Translate():
    GUI.mainloop();
    

pilImage = Image.open("D:\WorkSpace\Project\Python_Project_BKACAD\GUI_Translate\img\logo-translate.png").resize((50,50));
test = ImageTk.PhotoImage(pilImage);

label = tkinter.Label(image=test);
label.image = test;
label.grid(column=1,row=0, padx=10, pady=20);

comboBox_1 = ttk.Combobox(GUI);

comboBox_1['values'] = ('Auto Detect',
                        'afrikaans',
                        'albanian',
                        'amharic',
                        'arabic',
                        'armenian',
                        'azerbaijani',
                        'basque',
                        'belarusian',
                        'bengali',
                        'bosnian',
                        'bulgarian',
                        'catalan',
                        'cebuano',
                        'chichewa',
                        'chinese (simplified)',
                        'chinese (traditional)',
                        'corsican',
                        'croatian',
                        'czech',
                        'danish',
                        'dutch',
                        'english',
                        'esperanto',
                        'estonian',
                        'filipino',
                        'finnish',
                        'french',
                        'frisian',
                        'galician',
                        'georgian',
                        'german',
                        'greek',
                        'gujarati',
                        'haitian creole',
                        'hausa',
                        'hawaiian',
                        'hebrew',
                        'hebrew',
                        'hindi',
                        'hmong',
                        'hungarian',
                        'icelandic',
                        'igbo',
                        'indonesian',
                        'irish',
                        'italian',
                        'japanese',
                        'javanese',
                        'kannada',
                        'kazakh',
                        'khmer',
                        'korean',
                        'kurdish (kurmanji)',
                        'kyrgyz',
                        'lao',
                        'latin',
                        'latvian',
                        'lithuanian',
                        'luxembourgish',
                        'macedonian',
                        'malagasy',
                        'malay',
                        'malayalam',
                        'maltese',
                        'maori',
                        'marathi',
                        'mongolian',
                        'myanmar (burmese)',
                        'nepali',
                        'norwegian',
                        'odia',
                        'pashto',
                        'persian',
                        'polish',
                        'portuguese',
                        'punjabi',
                        'romanian',
                        'russian',
                        'samoan',
                        'scots gaelic',
                        'serbian',
                        'sesotho',
                        'shona',
                        'sindhi',
                        'sinhala',
                        'slovak',
                        'slovenian',
                        'somali',
                        'spanish',
                        'sundanese',
                        'swahili',
                        'swedish',
                        'tajik',
                        'tamil',
                        'telugu',
                        'thai',
                        'turkish',
                        'ukrainian',
                        'urdu',
                        'uyghur',
                        'uzbek',
                        'vietnamese',
                        'welsh',
                        'xhosa',
                        'yiddish',
                        'yoruba',
                        'zulu'
)

comboBox_1.grid(column=0, row=1, padx=20, pady=20);

comboBox_2 = ttk.Combobox(GUI);
comboBox_2.grid(column=2,row=1, padx=10, pady=20);

comboBox_2['values'] = ('afrikaans',
                        'albanian',
                        'amharic',
                        'arabic',
                        'armenian',
                        'azerbaijani',
                        'basque',
                        'belarusian',
                        'bengali',
                        'bosnian',
                        'bulgarian',
                        'catalan',
                        'cebuano',
                        'chichewa',
                        'chinese (simplified)',
                        'chinese (traditional)',
                        'corsican',
                        'croatian',
                        'czech',
                        'danish',
                        'dutch',
                        'english',
                        'esperanto',
                        'estonian',
                        'filipino',
                        'finnish',
                        'french',
                        'frisian',
                        'galician',
                        'georgian',
                        'german',
                        'greek',
                        'gujarati',
                        'haitian creole',
                        'hausa',
                        'hawaiian',
                        'hebrew',
                        'hebrew',
                        'hindi',
                        'hmong',
                        'hungarian',
                        'icelandic',
                        'igbo',
                        'indonesian',
                        'irish',
                        'italian',
                        'japanese',
                        'javanese',
                        'kannada',
                        'kazakh',
                        'khmer',
                        'korean',
                        'kurdish (kurmanji)',
                        'kyrgyz',
                        'lao',
                        'latin',
                        'latvian',
                        'lithuanian',
                        'luxembourgish',
                        'macedonian',
                        'malagasy',
                        'malay',
                        'malayalam',
                        'maltese',
                        'maori',
                        'marathi',
                        'mongolian',
                        'myanmar (burmese)',
                        'nepali',
                        'norwegian',
                        'odia',
                        'pashto',
                        'persian',
                        'polish',
                        'portuguese',
                        'punjabi',
                        'romanian',
                        'russian',
                        'samoan',
                        'scots gaelic',
                        'serbian',
                        'sesotho',
                        'shona',
                        'sindhi',
                        'sinhala',
                        'slovak',
                        'slovenian',
                        'somali',
                        'spanish',
                        'sundanese',
                        'swahili',
                        'swedish',
                        'tajik',
                        'tamil',
                        'telugu',
                        'thai',
                        'turkish',
                        'ukrainian',
                        'urdu',
                        'uyghur',
                        'uzbek',
                        'vietnamese',
                        'welsh',
                        'xhosa',
                        'yiddish',
                        'yoruba',
                        'zulu'
)

boxTextArea_1 = Text(GUI, width = 40, height = 10);
boxTextArea_1.grid(column=0, row=2, padx=10, pady=10);

boxTextArea_2 = Text(GUI, width = 40, height = 10);
boxTextArea_2.grid(column=2, row=2, padx=10, pady=10);

btnTranslate = Button(GUI,text='Translate',width=15, background="white", command=Controller.translate);
btnTranslate.grid(column=0, row=3, padx=10, pady=10);

btnTranslate = Button(GUI,text='Clear',width=15, background="white", command=Controller.Clear);
btnTranslate.grid(column=2, row=3, padx=10, pady=10);
